server.port: 5000

jasypt:
  passwordName: JASYPT_PASSWORD
  postgres:
    url: jdbc:postgresql://localhost/
    dbName: 5f4iEGq1ktgq2pggAGV+/A==
    username: Dyyf9Ao7KkG4LAoRwZsNIYfd2outTYao
    password: TNKoHuelZHlW3wx91Kk9fg==

spring:
  jpa.generate-ddl: true

message.seed:
  non-exist:
    code: non-exist.code
    args: []
  default-locale-code: en

i18n:
  defaultLocale: en
  encoding: UTF-8
  resource: classpath:translations
  providedLocales:
    - en
    - ru

initial.entities:
  enable: false
  directory: initialEntities
  paths:
    tags: tags.json
    countries: countries.json
    regions: regions.json
    cities: cities.json
    streets: streets.json
    addresses: addresses.json
  ids:
    tags: TAGS
    countries: COUNTRIES
    regions: REGIONS
    cities: CITIES
    streets: STREETS
    addresses: ADDRESSES