server.port: 5000

jasypt:
  passwordName: JASYPT_PASSWORD
  postgres:
    url: jdbc:postgresql://localhost/
    dbName: 5f4iEGq1ktgq2pggAGV+/A==
    username: Dyyf9Ao7KkG4LAoRwZsNIYfd2outTYao
    password: TNKoHuelZHlW3wx91Kk9fg==

spring:
  jpa.generate-ddl: true

message.seed:
  non-exist:
    code: non-exist.code
    args: []
  default-locale-code: en

i18n:
  defaultLocale: en
  encoding: UTF-8
  resource: classpath:translations
  providedLocales:
    - en
    - ru

initial.entities:
  enable: true
  directory: devInitialEntities
  sequence:
    - {key: TAGS, path: tags.json}
#    - {key: COUNTRIES, path: countries.json}
#    - {key: REGIONS, path: regions.json}
#    - {key: CITIES, path: cities.json}
#    - {key: STREETS, path: streets.json}
#    - {key: ADDRESSES, path: addresses.json}