server.port: 5000

jasypt:
  passwordName: JASYPT_PASSWORD
  postgres:
    url: jdbc:postgresql://localhost/
    dbName: YLO21L6CWBODK/eL0+/AFg==
    username: Dyyf9Ao7KkG4LAoRwZsNIYfd2outTYao
    password: TNKoHuelZHlW3wx91Kk9fg==

spring:
  jpa.generate-ddl: true

message.seed:
  non-exist:
    code: non-exist.code
    args: []
  default-locale-code: en

i18n:
  defaultLocale: en
  encoding: UTF-8
  resource: classpath:translations
  providedLocales:
    - en
    - ru

initial.entities:
  enable: false
  directory: prodInitialEntities

generators.alias.class:
  prefix: "gui.alias.class."