server.port: 5000

jasypt:
  passwordName: JASYPT_PASSWORD
  postgres:
    url: jdbc:postgresql://localhost/
#    prod
#    dbName: YLO21L6CWBODK/eL0+/AFg==
#    dev
    dbName: 5f4iEGq1ktgq2pggAGV+/A==
    username: Dyyf9Ao7KkG4LAoRwZsNIYfd2outTYao
    password: TNKoHuelZHlW3wx91Kk9fg==

spring:
  jpa.generate-ddl: true

message.seed:
  non-exist:
    code: non-exist.code
    args: []
  default-locale-code: en