export const AUTH = {
	LOGIN: {
		REQUEST: 'AUTH_LOGIN_REQUEST',
		RESPONSE: 'AUTH_LOGIN_RESPONSE',
		SUCCESS: 'AUTH_LOGIN_SUCCESS',
		ERROR: 'AUTH_LOGIN_ERROR'
	},
	LOGOUT: {
		REQUEST: 'AUTH_LOGOUT_REQUEST',
		RESPONSE: 'AUTH_LOGOUT_RESPONSE',
		SUCCESS: 'AUTH_LOGOUT_SUCCESS',
		ERROR: 'AUTH_LOGOUT_ERROR'
	},
	STATUS: {
		LOADING: 'AUTH_STATUS_LOADING',
		SUCCESS: 'AUTH_STATUS_SUCCESS',
		ERROR: 'AUTH_STATUS_ERROR',
		LOGOUT: 'AUTH_STATUS_LOGOUT',
		DISCONNECTED: 'AUTH_STATUS_DISCONNECTED'
	},
	ON: {
		DISCONNECTED: 'AUTH_ON_DISCONNECTED'
	}
};
