export const DOMAIN = {
	TAG: {
		REQUEST: {
			CREATE: 'DOMAIN_REQUEST_TAG_CREATE',
			UPDATE: 'DOMAIN_REQUEST_TAG_UPDATE',
			DELETE: 'DOMAIN_REQUEST_TAG_DELETE'
		},
		RESPONSE: {
			CREATE: 'DOMAIN_RESPONSE_TAG_CREATE',
			UPDATE: 'DOMAIN_RESPONSE_TAG_UPDATE',
			DELETE: 'DOMAIN_RESPONSE_TAG_DELETE'
		},
	}
};
