export const CONNECTION_CREATE = 'CONNECTION_CREATE';
export const CONNECTION_CONNECT = 'CONNECTION_CONNECT';
export const CONNECTION_DISCONNECT = 'CONNECTION_DISCONNECT';
export const CONNECTION_SEND = 'CONNECTION_SEND';
