const SUBSCRIPTION_CLIENT_PARAMS = 'SUBSCRIPTION_CLIENT_PARAMS';
const SUBSCRIPTION_I18N = 'SUBSCRIPTION_I18N';
const SUBSCRIPTION_AUTH_REQUEST = 'SUBSCRIPTION_AUTH_REQUEST';
const SUBSCRIPTION_LOGOUT_REQUEST = 'SUBSCRIPTION_LOGOUT_REQUEST';

const SUBSCRIPTIONS = {
	[SUBSCRIPTION_CLIENT_PARAMS]: '/topic/clientParamsResponse/',
	[SUBSCRIPTION_I18N]: '/topic/i18nResponse/',
	[SUBSCRIPTION_AUTH_REQUEST]: '/topic/authResponse/',
	[SUBSCRIPTION_LOGOUT_REQUEST]: '/topic/logoutResponse/'
};

export {
	SUBSCRIPTIONS,
	SUBSCRIPTION_CLIENT_PARAMS,
	SUBSCRIPTION_I18N,
	SUBSCRIPTION_AUTH_REQUEST,
	SUBSCRIPTION_LOGOUT_REQUEST
};
